#!/usr/bin/env python
# coding: ascii

"""
Automatically generated by django. Offers a developer interface.
"""
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "variety_trials_website.settings")

    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
